apiVersion: v1
kind: Secret
metadata:
  name: user-service
  namespace: backend
type: Opaque
data:
  DB_USER: anpseXk=
  DB_PASSWORD: cXpodWZ1Y2hlbmd6MTIzKg==
  REDIS_PASSWORD: cmVkaXM=
  RABBITMQ_USER: YWRtaW4=
  RABBITMQ_PASSWORD: cmFiYml0bXE=
  NACOS_USERNAME: bmFjb3M=
  NACOS_PASSWORD: bmFjb3M=
  JWT_SECRET: RzltQ1ExOW9nVGt1V1FZOWpIMndHWkFTdUdpL0pyaHN0UWFaeTRrLzAxbz0=
  SENDGRID_API_KEY: U0cueUstUXhudzdUdUc3STJMNHZra0hWUS5tLW1kXzI4R04wNmdwd3Z2NWpRckpWX3JYd3doYmtkLXdJOFBmNmNiYTFF
